sudo: false

language: python

python:
  - 3.9
  - 3.10
  - 3.11
  - 3.12

install:
  - pip install coveralls
  - pipenv install

script:
  - coverage run --source=mirage_test setup.py test

after_success:
  - coveralls
